package de.hdm.getthepoint.server.db.model;

// Generated 28.11.2014 00:27:43 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Ergebnis generated by hbm2java
 */
@Entity
@Table(name = "Ergebnis", catalog = "getthepointdb")
public class Ergebnis implements java.io.Serializable {

	private static final long serialVersionUID = 5584124139779938194L;
	private int id;
	private Antwort antwort;
	private Frage frage;
	private Student student;
	private Wissenstest wissenstest;
	private Character richtig;

	public Ergebnis() {
	}

	public Ergebnis(int id) {
		this.id = id;
	}

	public Ergebnis(int id, Antwort antwort, Frage frage, Student student,
			Wissenstest wissenstest, Character richtig) {
		this.id = id;
		this.antwort = antwort;
		this.frage = frage;
		this.student = student;
		this.wissenstest = wissenstest;
		this.richtig = richtig;
	}

	@Id
	@GeneratedValue
	@GenericGenerator(name = "increment", strategy = "increment")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "antwort-id")
	public Antwort getAntwort() {
		return this.antwort;
	}

	public void setAntwort(Antwort antwort) {
		this.antwort = antwort;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "frage-id")
	public Frage getFrage() {
		return this.frage;
	}

	public void setFrage(Frage frage) {
		this.frage = frage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student-id")
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "wissenstest-id")
	public Wissenstest getWissenstest() {
		return this.wissenstest;
	}

	public void setWissenstest(Wissenstest wissenstest) {
		this.wissenstest = wissenstest;
	}

	@Column(name = "richtig", length = 1)
	public Character getRichtig() {
		return this.richtig;
	}

	public void setRichtig(Character richtig) {
		this.richtig = richtig;
	}

}
