package de.hdm.getthepoint.server.db.model;

// Generated 28.11.2014 00:27:43 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Frage generated by hbm2java
 */
@Entity
@Table(name = "Frage", catalog = "getthepointdb")
public class Frage implements java.io.Serializable {

	private static final long serialVersionUID = 3577709284319289851L;
	private int id;
	private Antwort antwort;
	private Integer kategorieId;
	private String text;
	private Integer schwierigkeit;
	private byte[] bild;
	private Set<ZuordungWissenstestFrage> zuordungWissenstestFrages = new HashSet<ZuordungWissenstestFrage>(
			0);
	private Set<Antwort> antworts = new HashSet<Antwort>(0);
	private Set<Ergebnis> ergebnises = new HashSet<Ergebnis>(0);

	public Frage() {
	}

	public Frage(int id) {
		this.id = id;
	}

	public Frage(int id, Antwort antwort, Integer kategorieId, String text,
			Integer schwierigkeit, byte[] bild,
			Set<ZuordungWissenstestFrage> zuordungWissenstestFrages,
			Set<Antwort> antworts, Set<Ergebnis> ergebnises) {
		this.id = id;
		this.antwort = antwort;
		this.kategorieId = kategorieId;
		this.text = text;
		this.schwierigkeit = schwierigkeit;
		this.bild = bild;
		this.zuordungWissenstestFrages = zuordungWissenstestFrages;
		this.antworts = antworts;
		this.ergebnises = ergebnises;
	}

	@Id
	@GeneratedValue
	@GenericGenerator(name = "increment", strategy = "increment")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "loesung")
	public Antwort getAntwort() {
		return this.antwort;
	}

	public void setAntwort(Antwort antwort) {
		this.antwort = antwort;
	}

	@Column(name = "kategorie-id")
	public Integer getKategorieId() {
		return this.kategorieId;
	}

	public void setKategorieId(Integer kategorieId) {
		this.kategorieId = kategorieId;
	}

	@Column(name = "text", length = 45)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "schwierigkeit")
	public Integer getSchwierigkeit() {
		return this.schwierigkeit;
	}

	public void setSchwierigkeit(Integer schwierigkeit) {
		this.schwierigkeit = schwierigkeit;
	}

	@Column(name = "bild")
	public byte[] getBild() {
		return this.bild;
	}

	public void setBild(byte[] bild) {
		this.bild = bild;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "frage")
	public Set<ZuordungWissenstestFrage> getZuordungWissenstestFrages() {
		return this.zuordungWissenstestFrages;
	}

	public void setZuordungWissenstestFrages(
			Set<ZuordungWissenstestFrage> zuordungWissenstestFrages) {
		this.zuordungWissenstestFrages = zuordungWissenstestFrages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "frage")
	public Set<Antwort> getAntworts() {
		return this.antworts;
	}

	public void setAntworts(Set<Antwort> antworts) {
		this.antworts = antworts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "frage")
	public Set<Ergebnis> getErgebnises() {
		return this.ergebnises;
	}

	public void setErgebnises(Set<Ergebnis> ergebnises) {
		this.ergebnises = ergebnises;
	}

}
