package de.hdm.getthepoint.server.db.model;

// Generated 28.11.2014 00:27:43 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Kategorie generated by hbm2java
 */
@Entity
@Table(name = "Kategorie", catalog = "getthepointdb")
public class Kategorie implements java.io.Serializable {

	private static final long serialVersionUID = -2737967994178634065L;
	private int id;
	private Lehrender lehrender;
	private String bezeichnung;

	public Kategorie() {
	}

	public Kategorie(int id) {
		this.id = id;
	}

	public Kategorie(int id, Lehrender lehrender, String bezeichnung) {
		this.id = id;
		this.lehrender = lehrender;
		this.bezeichnung = bezeichnung;
	}
	
	@Id
	@GeneratedValue
	@GenericGenerator(name = "increment", strategy = "increment")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	
	@JoinColumn(name = "lehrender-id")
	public Lehrender getLehrender() {
		return this.lehrender;
	}

	public void setLehrender(Lehrender lehrender) {
		this.lehrender = lehrender;
	}

	@Column(name = "bezeichnung", length = 45)
	public String getBezeichnung() {
		return this.bezeichnung;
	}

	public void setBezeichnung(String bezeichnung) {
		this.bezeichnung = bezeichnung;
	}

}
